backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_fodler: "/images/uploads"
collections:
  - name: "accomplishments" # Used in routes, e.g., /admin/collections/blog
    label: "Accomplishments" # Used in the UI
    folder: "src/content/accomplishments" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD" # e.g. 24.12.2021
        format: "L"
        picker_utc: false
      - {label: "Subline", name: "subline", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Media"
        name: "media"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        default: [""]
  - name: "notices" # Used in routes, e.g., /admin/collections/blog
    label: "Notices" # Used in the UI
    folder: "src/content/notices" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "postDate"
        widget: "datetime"
        date_format: "YYYY-MM-DD" # e.g. 24.12.2021
        format: "L"
        picker_utc: false
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
  - name: "sessions" # Used in routes, e.g., /admin/collections/blog
    label: "Sessions" # Used in the UI
    folder: "src/content/sessions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        date_format: "YYYY-MM-DD" # e.g. 24.12.2021
        format: "L"
        picker_utc: false
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 0
        value_type: "int"
  - name: "resources" # Used in routes, e.g., /admin/collections/blog
    label: "Resources" # Used in the UI
    folder: "src/content/resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "lastUpdated"
        widget: "datetime"
        date_format: "YYYY-MM-DD" # e.g. 24.12.2021
        format: "L"
        picker_utc: false
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", default: ""}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Colors"
        name: "colors"
        widget: "list"
        default: ["#FFBEBE", "#F99973"]
        min: 2
        max: 2
        field: { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }